name: Update Version
run-name: Update Version ${{ github.event.inputs.major_version }} and ${{ github.event.inputs.target }}

on:
  workflow_dispatch:
    inputs:
      target:
        description: The tag or reference to use
        required: true
      major_version:
        type: choice
        description: The major version to update
        options:
          - v2

jobs:
  tag:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write  # This is required for pushing tags

    steps:
    # Note this update workflow can also be used as a rollback tool.
    # For that reason, it's best to pin `actions/checkout` to a known, stable version
    # (typically, about two releases back).
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0
    - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 24.18.0
    - run: |
        npm ci
        npm run build
    - name: Git config
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: Add built files
      run: git add -A && git commit -m "Update version to ${{ github.event.inputs.target }}"
    - name: Tag new target
      run: |
        git tag -a ${{ github.event.inputs.target }} -m "Update version to ${{ github.event.inputs.target }}"
        git tag -f ${{ github.event.inputs.major_version }} ${{ github.event.inputs.target }}
    - name: Push new tag
      run: |
        git push origin ${{ github.event.inputs.major_version }} --force --tags
